version: '3'
services:
#mssql docker
  vgfeed-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - vgfeednet

  vgfeed-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:VGFeed=Server=vgfeed-sql,1433;Database=3123;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 5000:80
    networks:
      - vgfeednet
    links:
      - vgfeed-sql
    depends_on:
      - vgfeed-sql
      
networks:
  vgfeednet:
    driver: bridge      